a = int(input("Enter "))
b = int(input("Enter "))
print('Addition Value is:',a+b)
print("Subtraction Value is:",a-b)
print("Multiplication Value is:",a*b)
print("Division Value is:",a/b)
print("Exponential Value is:",a**b)
print("Floor Division Value is:",a//b)
print("Remainder Value is:",a%b)
